apiVersion: v1
kind: Secret
metadata:
  name: backend-vault
  namespace: production
type: Opaque # Standard type for most data
data:
  # These MUST be base64 encoded strings
  DB_PASSWORD: bXktc3VwZXItc2VjcmV0LXBhc3N3b3Jk
  SSL_CERT: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0t... (truncated binary string)



# How to use it in your YAML
# You use it exactly like a ConfigMap, but with secretKeyRef.

spec:
  containers:
    - name: app
      image: my-app:v1
      env:
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-vault
              key: DB_PASSWORD
      # MOUNTING AS A FILE (Common for Binary Files)
      volumeMounts:
        - name: cert-volume
          mountPath: "/etc/ssl/certs"
          readOnly: true
  volumes:
    - name: cert-volume
      secret:
        secretName: backend-vault
