# Now imagine you are installing a cluster-wide monitoring system like Prometheus. Prometheus needs to scrape metrics from every node and every pod in every namespace across the entire cluster. A standard Role won't work because it is trapped in one namespace. We need a ClusterRole.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # Notice: NO namespace field here! ClusterRoles are global.
  name: global-metrics-reader
rules:
- apiGroups: [""]
  resources: ["nodes", "pods", "services"]
  verbs: ["get", "list", "watch"]
