# 1. Which version of the K8s API to use
apiVersion: v1

# 2. What kind of resource are we creating?
kind: Pod

# 3. Data that helps identify the resource (Name, Labels)
metadata:
  name: pod_name

# 4. The actual configuration of the containers
spec:
  containers:
    name: container_name
    image: nginx:latest
    ports:
      containerPort: 80
