apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: webapp-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: webapp

  minReplicaCount: 1
  maxReplicaCount: 10

  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "70"
