# Imagine you have an automation script running inside a Pod that needs to list and delete Pods inside the testing namespace only.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-cleaner-sa
  namespace: testing
