# PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notes-app-pvc
  namespace: notes-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

# Deployment (using the PVC)

apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-app-deployment
  namespace: notes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-app
  template:
    metadata:
      labels:
        app: notes-app
    spec:
      containers:
      - name: notes-app
        image: ritesh1973/notes-app:latest
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: notes-storage
          mountPath: /data   # 👈 inside container
      volumes:
      - name: notes-storage
        persistentVolumeClaim:
          claimName: notes-app-pvc
