apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data-pvc
  namespace: monitoring
  labels:
    app: prometheus
    storage-tier: gold
spec:
  # The StorageClass is the 'Service Tier' (e.g., SSD, HDD, etc.)
  # Most companies define 'standard', 'fast', or 'premium-ssd'
  storageClassName: premium-ssd 
  
  accessModes:
    - ReadWriteOnce # One node at a time can write (standard for DBs)
  
  resources:
    requests:
      storage: 100Gi # The amount of space requested
      
  # Optional: Selector to pick a specific pre-existing PV
  # selector:
  #   matchLabels:
  #     release: "stable"



# Deployment


  spec:
  containers:
    - name: prometheus
      image: prom/prometheus:v2.45.0
      volumeMounts:
        - name: data-disk # Must match the volume name below
          mountPath: /prometheus # The folder inside the container
  volumes:
    - name: data-disk
      persistentVolumeClaim:
        claimName: prometheus-data-pvc # Link to the PVC created above
